# Mais informações sobre o arquivo de configuração podem ser encontradas aqui:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[default]
[default.global.parameters]
stack_name = "liq-convert"

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"

# Adicione os caminhos dos arquivos das funções Lambda
[default.lambda_handler_paths]
  # Função Lambda para a API Gateway
  createUserController = "createUserController.handler"

  # Função Lambda para o SQS
  sqsLambdaHandler = "sqsLambdaHandler.handler"
